### PR TITLE
feat: repo template additions

### PR DESCRIPTION
**Pull request by mmoyaferrer**
- Added prettier, added its configuration
- Prettied repository contents
- Upgraded husky (not properly working before), and configured it to run prettier on precommit
- Added PMD and ruleset
- Added VSCode configuration to editor, PMD and prettier
- Added VSCode extension recommendations
- Added main Hutte Recipes
    - Incremental deployments recipe
    - Code Quality Scanner Recipe
    - SFDMU Recipe 
  
Added:
- Hutte Project Template project in Hutte QA

### CODE REVIEW

**Comment by mmoyaferrer** [comment]
@hmayerhutte , creating this as a Draft PR for early collaboration and feedback. I'm still missing some points to do which I covered in the description of this PR.

**Comment by mmoyaferrer** [comment]
@amtrack , happy to get suggestions from your side in this PR :)

**Comment by hmayerhutte** [comment]
This looks awesome @mmoyaferrer !
Only doubt I have is about using 4 spaces as indent - this changes XML metadata from the default (and in general for my personal preference it looks too much whitespace, but that's probably just a matter of taste)

**Comment by mmoyaferrer** [comment]
> This looks awesome @mmoyaferrer ! Only doubt I have is about using 4 spaces as indent - this changes XML metadata from the default (and in general for my personal preference it looks too much whitespace, but that's probably just a matter of taste)

Let me change it, I feel comfortable with both, just put my default.

**Comment by mmoyaferrer** [comment]
> > This looks awesome @mmoyaferrer ! Only doubt I have is about using 4 spaces as indent - this changes XML metadata from the default (and in general for my personal preference it looks too much whitespace, but that's probably just a matter of taste)
> 
> Let me change it, I feel comfortable with both, just put my default.

Done

**Comment by hmayerhutte** [comment]
hi @mmoyaferrer thank you! could you inspect why the last build is failing with:

fatal: empty ident name (for <runner@fv-az1016-860.pv3vitign2bulj5h5vrau5ekvd.cx.internal.cloudapp.net>) not allowed
Error: Process completed with exit code 128.

thanks!

**Comment by mmoyaferrer** [comment]
> hi @mmoyaferrer thank you! could you inspect why the last build is failing with:
> 
> fatal: empty ident name (for [runner@fv-az1016-860.pv3vitign2bulj5h5vrau5ekvd.cx.internal.cloudapp.net](mailto:runner@fv-az1016-860.pv3vitign2bulj5h5vrau5ekvd.cx.internal.cloudapp.net)) not allowed Error: Process completed with exit code 128.
> 
> thanks!

Fixed, `deltas` folder was not being ignored

**Review by hmayerhutte — APPROVED** [review]

**Comment by amtrack** [comment]
> This looks awesome @mmoyaferrer ! Only doubt I have is about using 4 spaces as indent - this changes XML metadata from the default (and in general for my personal preference it looks too much whitespace, but that's probably just a matter of taste)

@hmayerhutte As far as I know, the default is 4 spaces 😄  This applies to metadata files like `*-meta.xml` and also Apex Classes, etc.

Examples:
- [some metadata from ebikes-lwc](https://github.com/trailheadapps/ebikes-lwc/blob/main/force-app/main/default/networkBranding/cbE_Bikes.networkBranding-meta.xml)
- [some ApexClass from ebikes-lwc](https://github.com/trailheadapps/ebikes-lwc/blob/main/force-app/main/default/classes/ProductController.cls)

**Review by amtrack — APPROVED** [review]
Looks good to me! I'd only like to have 4 spaces because I think this is the default.

**Comment by hmayerhutte** [comment]
sorry for causing confusion with my ask for different indent .. that was motivated by seeing a metadata diff which I might have mis-interpreted... I'm of course fine with the default, so that users don't get a whitespace-diff when they update any of the metadata in salesforce and re-retrieve!
thx

**Pull request merged**
